require 'rubygems'

# Set up gems listed in the Gemfile.
gemfile = File.expand_path('Gemfile', __FILE__)
begin
  ENV['BUNDLE_GEMFILE'] = gemfile
  require 'bundler'
  Bundler.setup
rescue Bundler::GemNotFound => e
  STDERR.puts e.message
  STDERR.puts "Try running `bundle install`."
  exit!
end if File.exist?(gemfile)
require "chef_cap"
load 'deploy' if respond_to?(:namespace) # cap2 differentiator
::ChefCap::Capistrano.load_recipes(self)
Dir['vendor/plugins/*/recipes/*.rb'].each { |plugin| load(plugin) }
load 'config/deploy'
